### ISSUE TITLE
Filtering with empty filter Map possibly broken

### ISSUE THREAD

**Issue by quwisky** [biagioT/jpa-search-helper#4]
@biagioT first of all I would like to say thank you for your amazing work on this library.

We have been using the 1.0.3 version, but after we moved to version 3.1.0 we started to get `app.tozzi.exception.JPASearchException: Invalid expression: empty filters` errors when we tried to fetch data with empty filter map.

My question is that it's an intended change, that library does not support fetching data without filters or this should work and we are the ones doing something wrong?

**Comment by biagioT** [comment]
Hi, thanks for the appreciation!

Yes, it was an intentional choice, but I realize that it would make sense to allow search without filters (**but only if you don't choose to use a repository method that involves sorting or pagination**).

I have just released 3.1.1 which, like what was written before, provides search without filters (it will take just the time to index the Maven Central Repository)
I recommend you switch to 3.x soon.

**Comment by quwisky** [comment]
Thanks for the fast response!
Can I ask why you decided to only support this without sorting or pagination?

**Comment by biagioT** [comment]
It would not make sense to perform an ordered and/or paginated search without indicating the ordering and/or sorting parameters.

**Comment by quwisky** [comment]
Ofc, sorry, I'm a bit tired today, I misunderstood what you wrote before, it's totally reasonable.

Thanks again for the fast fix.

**Comment by quwisky** [comment]
Sorry for bothering you again, but I just looked through your changes and I think you should not return `null` here:
https://github.com/biagioT/jpa-search-helper/blob/main/src/main/java/app/tozzi/core/JPASearchCore.java#L30

According to the `JpaSpecificationExecutor` interface's documentation the findAll method's spec parameter must not be null, maybe it would be better to do something like these:
```java
if (filter == null) {
    return Specification.where(null);
}
```
or
```java
if (filter == null) {
    return (root, query, criteriaBuilder) -> null;
}
```

I'm not a JPA expert myself, so please feel free to tell me if I'm totally wrong.

**Comment by biagioT** [comment]
Which version of `JpaSpecificationExecutor` are you referring to? [Here](https://docs.spring.io/spring-data/jpa/docs/3.3.x/api/org/springframework/data/jpa/repository/JpaSpecificationExecutor.html) it is written that in the various `findAll(...)` methods, `spec` can be null. This is the version of spring-data in matrix with the current jpa-search-helper (3.x.x). In fact [this](https://github.com/biagioT/jpa-search-helper/blob/030402074e51305fbe63c042e182dd5cd054c953/src/test/java/app/tozzi/core/JPASearchCoreTest.java#L186C17-L186C38) test works.

In any case, as a matter of elegance and style of the code, I would say that your proposal is correct. I will make this change in future versions.

Finally, I remind you that there is an _ad hoc_ [project](https://github.com/biagioT/jpa-search-helper-demo) where you can try the library in action, in its two modes, via REST/HTTP endpoints.

**Comment by quwisky** [comment]
I looked it up in spring's repository and you are absolutely right, your change should work, there documentation was misleading and they only updated it in version 3.3.2: https://github.com/spring-projects/spring-data-jpa/commit/871b1b627d4189d30e9116f873aed880add96927
